name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r data-exposure-api/requirements.txt

      # Paso 4: Ejecutar pruebas (si tienes)
      - name: Run Tests
        run: |
          source venv/bin/activate
          # Asegúrate de tener tests en un directorio como tests/
          pytest tests/

      # Paso 5: Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 6: Autenticarse en Google Cloud
      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build and Push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/data-exposure-api:${{ github.sha }} ./data-exposure-api
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/data-exposure-api:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy data-exposure-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/data-exposure-api:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
